version: '3'
services:
  frontend:
    container_name: qr-frontend
    pull_policy: build
    network_mode: bridge
    restart: always
    env_file:
      - stack.env
    build: ./frontend
    ports:
      - "35632:3000"
    depends_on:
      - backend
  backend:
    container_name: qr-backend
    pull_policy: build
    network_mode: bridge
    restart: always
    env_file:
      - stack.env
    build: ./backend
    ports:
      - "33026:8080"